// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutText from "@/components/sections/about/AboutText";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
              <AboutText
                textAnimation="slide-up"
                title="For over two decades, we've been California's trusted destination for luxury dental care, combining advanced technology with artistic precision to create beautiful, healthy smiles that transform lives"
                primaryButton={{ text: "Meet Our Team", href: "#testimonials" }}
                secondaryButton={{ text: "Learn More", href: "#contact" }}
              />
            </div>
  );
}
