// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactSplitEmail from "@/components/sections/contact/ContactSplitEmail";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
              <ContactSplitEmail
                textAnimation="slide-up"
                tag="Get In Touch"
                title="Schedule Your Luxury Dental Experience"
                description="Connect with our team to discuss your smile goals and discover how our personalized treatments can transform your dental health and confidence."
                inputPlaceholder="Enter your email"
                buttonText="Get Started"
                imageSrc="https://storage.googleapis.com/webild/default/templates/dentist/contact/contact.avif"
              />
            </div>
  );
}
