// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesMediaCards from "@/components/sections/features/FeaturesMediaCards";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
              <FeaturesMediaCards
                textAnimation="slide-up"
                tag="Premium Dental Excellence"
                title="Why Choose Our Luxury Practice"
                description="We combine artistic excellence with scientific precision, utilizing the latest technology and techniques to deliver transformative results that exceed expectations."
                items={[
                  {
                    title: "Digital Technology",
                    description: "3D imaging, intraoral cameras, and computer-aided design for precise diagnostics and treatment planning.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/dentist/about/about1.avif",
                  },
                  {
                    title: "Master Craftsmanship",
                    description: "Award-winning dentists with decades of experience in cosmetic and restorative excellence.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/dentist/about/about2.avif",
                  },
                ]}
              />
            </div>
  );
}
