// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplitKpi from "@/components/sections/hero/HeroSplitKpi";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
              <HeroSplitKpi
        textAnimation="slide-up"
        tag="24/7 Emergency Dental Care"
        title="Emergency Dentist Jacksonville FL"
        description="Immediate, compassionate emergency dental care when you need it most. Available 24/7 for severe toothaches, broken teeth, and dental trauma."
        primaryButton={{"text":"Call Now for Emergency Care","href":"#contact"}}
        secondaryButton={{"text":"View Our Services","href":"#services"}}
        imageSrc="https://storage.googleapis.com/webild/default/templates/dentist/hero/hero1.avif"
        kpis={[{"label":"Emergency Patients Treated","value":"10k+"},{"label":"Response Time","value":"< 15 min"},{"label":"Available","value":"24/7"}]}
      />
            </div>
  );
}
