// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import ProductRatingCards from "@/components/sections/product/ProductRatingCards";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
              <ProductRatingCards
                textAnimation="slide-up"
                tag="Premium Dental Services"
                title="Our Signature Services"
                description="From cosmetic enhancement to restorative excellence, our comprehensive services transform smiles and improve oral health with precision and artistry."
                primaryButton={{ text: "Schedule Consultation", href: "#contact" }}
                products={[
                  {
                    brand: "Cosmetic",
                    name: "Smile Design & Whitening",
                    price: "From $500",
                    rating: 5,
                    reviewCount: "234",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/dentist/services/service1.avif",
                  },
                  {
                    brand: "Restorative",
                    name: "Dental Implants & Crowns",
                    price: "From $1,200",
                    rating: 5,
                    reviewCount: "312",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/dentist/services/service2.avif",
                  },
                  {
                    brand: "Advanced",
                    name: "Orthodontics & Aligners",
                    price: "From $800",
                    rating: 5,
                    reviewCount: "289",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/dentist/services/service3.avif",
                  },
                ]}
              />
            </div>
  );
}
