// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialMarqueeCards from "@/components/sections/testimonial/TestimonialMarqueeCards";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
              <TestimonialMarqueeCards
                textAnimation="slide-up"
                tag="Patient Reviews"
                title="What Our Patients Say"
                description="Discover why hundreds of California's discerning patients trust us for their dental care and smile transformations."
                testimonials={[
                  {
                    name: "Jennifer Martinez",
                    role: "San Diego Patient",
                    quote: "The most professional and caring dental experience I've ever had. The results exceeded my expectations and the attention to detail is extraordinary.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/luxury-travel-agency/testimonial/testimonial1.webp",
                  },
                  {
                    name: "Robert Chen",
                    role: "Business Executive",
                    quote: "Finally found a dentist who understands aesthetics and function. My smile is now my confidence. Highly recommended to anyone serious about quality.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/luxury-travel-agency/testimonial/testimonial2.webp",
                  },
                  {
                    name: "Sarah Williams",
                    role: "Entertainment Industry",
                    quote: "This is the place where art meets science. My smile transformation has been life-changing. The expertise here is unmatched.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/luxury-travel-agency/testimonial/testimonial3.webp",
                  },
                  {
                    name: "Michael Torres",
                    role: "Loyal Patient",
                    quote: "I've been a patient for 8 years. The consistent excellence, warm staff, and cutting-edge treatments keep me coming back with confidence.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/skincare/image5.avif",
                  },
                  {
                    name: "Amanda Rodriguez",
                    role: "Social Media Influencer",
                    quote: "When your smile matters for your career, you go to the best. This practice delivered a smile that's both beautiful and natural-looking.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/skincare/image6.avif",
                  },
                  {
                    name: "David Kim",
                    role: "Healthcare Professional",
                    quote: "The clinical precision combined with artistic vision is remarkable. This team truly understands comprehensive dental care at the highest level.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/skincare/image7.avif",
                  },
                ]}
              />
            </div>
  );
}
